/**
 * Dynamic Memory Retention System for Spectre AI
 *
 * This module implements a rolling buffer with intelligent summarization
 * to maintain long-term context while staying within token budget constraints.
 *
 * Architecture:
 * - Recent messages stored as raw text (full fidelity)
 * - Older messages compressed into summaries via Gemini
 * - Memory bank periodically re-summarized to prevent unbounded growth
 *
 * Benefits:
 * - Predictable token usage (prompt assembly targets ~30k Flash-Lite / ~50k Flash)
 * - Scales to arbitrarily long conversations
 * - Preserves critical context (decisions, code changes, intents)
 * - No hard-coded limits on message length
 *
 * @author Tazul Islam
 */

/**
 * Raw message with full content preserved in rolling buffer.
 */
export interface RawMessage {
  /** Unique identifier for tracking and summarization */
  id: string;

  /** Message role: user input or AI response */
  role: 'user' | 'assistant';

  /** Full message text */
  text: string;

  /** Full message parts (including thoughts) for Gemini 3 compliance */
  parts?: any[];

  /** Timestamp for aging and cleanup */
  timestamp: number;

  /** Estimated token count (cached for performance) */
  estimatedTokens?: number;
}

/**
 * Summarized representation of one or more old messages.
 * Generated by Gemini with focus on key decisions, intents, and code changes.
 */
interface SummaryEntry {
  /** Unique identifier */
  id: string;

  /** Condensed summary text focusing on actionable context */
  summary: string;

  /** IDs of original messages that were summarized */
  originalMessageIds: string[];

  /** Timestamp when summary was created */
  createdAt: number;

  /** Estimated token count (cached) */
  estimatedTokens?: number;

  /** Optional: categorization for better retrieval */
  category?:
    | 'code_change'
    | 'configuration'
    | 'debugging'
    | 'learning'
    | 'general';
}

/**
 * Memory bank: collection of summaries representing historical context.
 * Periodically re-summarized when approaching token cap.
 */
interface MemoryBank {
  /** All summary entries, oldest first */
  summaries: SummaryEntry[];

  /** Total estimated tokens across all summaries */
  totalTokens: number;

  /** Last time memory bank was re-summarized/compressed */
  lastCompressedAt?: number;

  /** Version for migration compatibility */
  version: number;
}

/**
 * Complete conversation state with dynamic memory management.
 */
export interface ConversationMemory {
  /** Session identifier */
  sessionId: string;

  /** Recent messages in rolling buffer (full fidelity) */
  recentMessages: RawMessage[];

  /** Compressed historical context */
  memoryBank: MemoryBank;

  /** Configuration for this conversation */
  config: MemoryConfig;

  /** Statistics for monitoring */
  stats: {
    totalInteractions: number;
    summarizationsPerformed: number;
    lastSummarizedAt?: number;
  };
}

/**
 * Configuration for memory retention behavior.
 */
interface MemoryConfig {
  /** Max raw messages to keep before summarization (defaults are set in `memory-manager.ts`, currently 40) */
  maxRecentMessages: number;

  /** Soft cap for memory bank tokens (defaults are set in `memory-manager.ts`, currently 100k) */
  memoryBankTokenCap: number;

  /** When to trigger summarization of recent messages */
  summarizationTrigger: {
    /** Min messages before considering summarization */
    minMessages: number;

    /** Or when recent messages exceed this token count */
    maxTokens: number;
  };

  /** When to re-compress the memory bank */
  compressionTrigger: {
    /** Percentage of cap before compressing (e.g., 0.8 = 80%) */
    threshold: number;
  };
}
